### PR TITLE
AZD + Aspire messaging template

### PR DESCRIPTION
**Pull request by alexwolfmsft**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/messaging/messaging-components.md](https://github.com/dotnet/docs-aspire/blob/1868f076f148373e8f1f234cb60627ed4ba4df8b/docs/messaging/messaging-components.md) | [Tutorial: Use .NET Aspire messaging components in ASP.NET Core](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-components?branch=pr-en-us-542) |

### CODE REVIEW

**Comment by davidfowl** [comment]
Why does this template have the infra folder checked in? Was that generated with azd infa synth?

**Comment by alexwolfmsft** [comment]
> Why does this template have the infra folder checked in? Was that generated with azd infa synth?

This tutorial doesn't have a deployment component - from an azd docs perspective, when we add azd to "local dev only" tutorials we sometimes create infrastructure-only templates that are designed to provision all of the resources necessary to connect to locally when running the app so the user doesn't have to take care of that part. 
This approach also provides the completed sample app code if they want to be able to just browse the completed app and optionally generate the corresponding azure resources.

**Comment by davidfowl** [comment]
IMO we don't want to show this with aspire. It taints the story a bit because this isn't the path we're going to be showing people. Manually authored bicep works but it always did and isn't really showing aspire in the light we intend it to be shown.

**Comment by davidfowl** [comment]
PS: We have a local dev against azure story for P5 with aspire that is not this developer experience.

**Comment by alexwolfmsft** [comment]
> IMO we don't want to show this with aspire. It taints the story a bit because this isn't the path we're going to be showing people. Manually authored bicep works but it always did and isn't really showing aspire in the light we intend it to be shown.

I understand the point here - maybe there is a flow where we can still provide the completed app as an azd template but not include the infra folder. The user could simply run azd init with "use code in current directory" and then azd provision instead of a full azd up with deployment. I could try this flow and see how it goes. 

If this is flow is still not ideal we could hold off on this until P5.

**Comment by davidfowl** [comment]
> If this is flow is still not ideal we could hold off on this until P5.

Yes please. I would love to spend energy documenting what we've build for P5.

**Pull request closed without merging**
