### PR TITLE
Remove AddBuiltInMeters()

### PR DESCRIPTION
**Pull request by martincostello**
## Summary

Update the documentation to use built-in OpenTelemetry instrumentation.

See https://github.com/dotnet/aspire/pull/2900.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/fundamentals/service-defaults.md](https://github.com/dotnet/docs-aspire/blob/7fc003425f3a76cba6ec07cf6b1464b677d710a3/docs/fundamentals/service-defaults.md) | [.NET Aspire service defaults](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/service-defaults?branch=pr-en-us-518) |

### CODE REVIEW

**Comment by IEvangelist** [comment]
This looks great, are there any other places where we need to update this? I haven't checked, but does this now match the `preview-4` _Extensions.cs_ file that the template for the **Service Defaults** project generates? If not, we'd probably have to wait for this, if it's part of `preview-5`.

**Comment by martincostello** [comment]
I _think_ it does, as I made the original changes (see PR linked to linked PR) back in January.

**Comment by IEvangelist** [comment]
Here's what I see for the preview-4 tag, which differs from this PR:

https://github.com/dotnet/aspire/blob/v8.0.0-preview.4.24156.9/src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/Extensions.cs

Would you be willing to update it to match this?

**Comment by martincostello** [comment]
Which bit are you referring to, is it the Process bit? From working on the linked PR I saw that that was removed yesterday.

**Comment by IEvangelist** [comment]
Sorry for not being clearer, here's the diff (Left side `preview-4` source and right is yours):

https://www.diffchecker.com/hdLIT9r1/

I'm saying that we should update yours to match what is currently in `preview-4`. Does that make sense?

**Comment by martincostello** [comment]
Maybe we just leave it until p5 once my other PR is merged? Otherwise it'll just need changing again.

**Pull request merged**
