### PR TITLE
Allow Anonymous By Default

### PR DESCRIPTION
**Pull request by WeihanLi**
## Summary

Since dotnet aspire dashboard is mainly for development, maybe it would be better to allow anonymous by default in a convenient way?

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/fundamentals/dashboard/standalone.md](https://github.com/dotnet/docs-aspire/blob/e72bc91dcea58fcfb1c89705afb5b12980f07119/docs/fundamentals/dashboard/standalone.md) | [Standalone .NET Aspire dashboard](https://review.learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/standalone?branch=pr-en-us-1871) |

### CODE REVIEW

**Comment by IEvangelist** [comment]
If @JamesNK is good with this, I am too.

**Comment by JamesNK** [comment]
Some form of auth is required by default because we want to be secure by default.

We worked hard to make auth easy to use and included an option to disable it if you want to. I don't know of any more changes we could make without compromising security.

**Comment by IEvangelist** [comment]
Hi @WeihanLi - I'm sorry, but it looks like this isn't something that we'd like to include as the default for the reasons outlined by James. Thank you for proposing this, but we're going to close this as it's a security concern. I hope you understand.

**Comment by WeihanLi** [comment]
@JamesNK @IEvangelist thanks very much , I understand the security concern, so I'm just trying to update the docker command only, it may still not a good practice for security, if it's acceptable to add another command without auth to make people get started more easily? Think we could add a security concern comment for the command without auth

**Comment by JamesNK** [comment]
I don't think the initial docker sample should have auth disabled. But, I hear you that it's useful to have the complete command somewhere that includes the flag to disable login. Gives something for people to copy and paste.

Maybe a new section could replace the tip in "Login to the dashboard" that discusses disabling auth and includes the command:

image

I'm not against having a command with auth disabled, it just shouldn't be the first one we give to people, and there needs to be some link or discussion about the risk involved.

**Comment by WeihanLi** [comment]
Think it does not make more sense to keep secure only for the dashboard. 
The dashboard has auth by default while no auth for the OTEL endpoint by default, that's not secure still. To be secure by default, think the auth for the OTEL endpoint should also be enabled by default.

**Comment by JamesNK** [comment]
> The dashboard has auth by default while no auth for the OTLP endpoint by default, that's not secure still. 

OTLP isn't secure by default because there is no way to secure it without external configuration. We migitate that with warnings in logs and UIs.

Frontend can have a good secure by default option so it is.

Security is important. We're not changing this.

**Comment by WeihanLi** [comment]
> OTLP isn't secure by default because there is no way to secure it without external configuration.

Is it possible to generate a random key if no configuration exists like the token for the dashboard?

**Comment by JamesNK** [comment]
Yes, but the random key would change each time the standalone dashboard is launched, which means apps sending telemetry to the dashboard would need to be updated. That's not a reasonable experience.

We chose to display warnings in logs and the UI that untrusted telemetry data could be sent to the dashboard.

**Comment by WeihanLi** [comment]
Get it, thanks very much for the detailed reply @JamesNK

**Pull request closed without merging**
